### ISSUE TITLE
can you remove the background blur when opening the settings or theme picker etc?

### ISSUE THREAD

**Issue by incantatem1** [Elhary/Obsidian-Minimal-Edge#1]
i preferred the original version which was without this, and it causes unnecessary lag, please either remove it or add an option to either show or not show it. i don't like the blur anyway in the otherwise really cool theme.

**Comment by Elhary** [comment]
I’ve added an option to turn off the blur in the latest update. Just make sure to update the theme, install the **"Style Settings"** plugin (if you haven't already), and go to **Style Settings**. Find **"Minimal Edge"** in the settings to toggle the blur off.

You can also change the theme, though it's still in development. I understand the original version without the blur was your preference, so I hope this option works better for you!

Feel free to let me know if you run into any issues.

**Comment by incantatem1** [comment]
nice update, thank you. i also enjoy that you're adding themes, even though the standard one is my favourite^^

**Comment by Elhary** [comment]
Thanks! I’m glad you liked the update and the themes! I’ll keep adding more, but it’s great to hear the standard one is your favorite. Let me know if you have any other feedback!

**Comment by incantatem1** [comment]
hmm. not sure what else i would suggest, maybe selectable border radius and border styles? no idea though, i almost only use my own themes at this point and rarely install ones from the gallery. this is one of the first in a while that i really enjoy for its uniqueness.

**Comment by Elhary** [comment]
Thanks for the suggestion! I’ll add border radius and border style options in the next update, along with more settings. Glad you’re enjoying the theme!

**Comment by incantatem1** [comment]
This theme just keeps getting better <3

**Comment by Elhary** [comment]
Thank you! I will keep making it even better!
